language: python
sudo: false

env:
  global:
    - PIP_DEPS="coveralls pytest-cov flake8"

python:
  - '3.6'

before_install:
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - travis_retry sudo apt-get update -qq
  #- travis_retry sudo apt-get install dcm2niix
  - git clone https://github.com/neurolabusc/dcm2niix
  - mkdir dcm2niix/build
  - cd dcm2niix/build
  - cmake ..
  - make
  - sudo cp bin/dcm2niix /usr/bin
  - travis_retry sudo apt-get install nodejs
  - npm install -g bids-validator

install:
- travis_retry pip install --upgrade pytest  # new pytest>3.3 for coveralls
- travis_retry pip install $PIP_DEPS
- cd $TRAVIS_BUILD_DIR
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- python download_test_data.py
- py.test --cov=bidsify/

after_success:
- coveralls
