#!/bin/bash
python setup.py sdist
python setup.py install
twine upload dist/bidsify-$1.tar.gz
./generate_dockerfile
./build_docker_image $1
docker push lukassnoek/bidsify:$1
docker push lukassnoek/bidsify:latest
